// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "todoApp3/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// TodoRepository is an autogenerated mock type for the TodoRepository type
type TodoRepository struct {
	mock.Mock
}

// CreateTodo provides a mock function with given fields: ctx, todo
func (_m *TodoRepository) CreateTodo(ctx context.Context, todo *domain.Todo) error {
	ret := _m.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Todo) error); ok {
		r0 = rf(ctx, todo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTodo provides a mock function with given fields: ctx, userID, todoID
func (_m *TodoRepository) DeleteTodo(ctx context.Context, userID uint, todoID uint) error {
	ret := _m.Called(ctx, userID, todoID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, userID, todoID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTodoByID provides a mock function with given fields: ctx, userID, todoID
func (_m *TodoRepository) GetTodoByID(ctx context.Context, userID uint, todoID uint) (*domain.Todo, error) {
	ret := _m.Called(ctx, userID, todoID)

	if len(ret) == 0 {
		panic("no return value specified for GetTodoByID")
	}

	var r0 *domain.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*domain.Todo, error)); ok {
		return rf(ctx, userID, todoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *domain.Todo); ok {
		r0 = rf(ctx, userID, todoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, userID, todoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTodos provides a mock function with given fields: ctx, page, limit, userID
func (_m *TodoRepository) GetTodos(ctx context.Context, page int, limit int, userID uint) ([]domain.Todo, int, error) {
	ret := _m.Called(ctx, page, limit, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTodos")
	}

	var r0 []domain.Todo
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, uint) ([]domain.Todo, int, error)); ok {
		return rf(ctx, page, limit, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, uint) []domain.Todo); ok {
		r0 = rf(ctx, page, limit, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, uint) int); ok {
		r1 = rf(ctx, page, limit, userID)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, uint) error); ok {
		r2 = rf(ctx, page, limit, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateTodo provides a mock function with given fields: ctx, todo
func (_m *TodoRepository) UpdateTodo(ctx context.Context, todo *domain.Todo) error {
	ret := _m.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Todo) error); ok {
		r0 = rf(ctx, todo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTodoRepository creates a new instance of TodoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoRepository {
	mock := &TodoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
